# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170811_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='download',
            field=models.URLField(blank=True),
        ),
    ]
