# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170811_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='download',
        ),
    ]
